# Generated by Django 5.0.7 on 2024-07-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannoli_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='( > u < )', max_length=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=256),
        ),
    ]
